var data = [
  {
    id: 0,
    career: "Civil Engineer",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "boy",
        age: "4",
      },
      {
        gender: "girl",
        age: "2",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 58540,
    montlyGross: 4878,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 6078,
    taxes: 530,
    subtotal: 5548,
    childSupport: 0,
    monthlyNet: 5348,
  },
  {
    id: 1,
    career: "Chemical Engineer",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "boy",
        age: "2",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 66730,
    montlyGross: 5560,
    spouseGrossIncome: 0,
    totalMonthlyGross: 5560,
    taxes: 508,
    subtotal: 5052,
    childSupport: 0,
    monthlyNet: 4852,
  },
  {
    id: 2,
    career: "Robotics Engineer",
    education: "College",
    edCost: 200,
    children: [],
    maritalStatus: "Single",
    anuualGross: 45988,
    montlyGross: 3832,
    spouseGrossIncome: 0,
    totalMonthlyGross: 3832,
    taxes: 481,
    subtotal: 3351,
    childSupport: 0,
    monthlyNet: 3151,
  },
  {
    id: 3,
    career: "Industrial Engineer",
    education: "College",
    edCost: 200,
    children: [],
    maritalStatus: "Single",
    anuualGross: 48421,
    montlyGross: 4035,
    spouseGrossIncome: 0,
    totalMonthlyGross: 4035,
    taxes: 531,
    subtotal: 3504,
    childSupport: 0,
    monthlyNet: 3304,
  },
  {
    id: 4,
    career: "Architect",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "7",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 51767,
    montlyGross: 4313,
    spouseGrossIncome: 0,
    totalMonthlyGross: 4313,
    taxes: 316,
    subtotal: 3997,
    childSupport: 0,
    monthlyNet: 3797,
  },
  {
    id: 5,
    career: "Surveyor",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 29913,
    montlyGross: 2494,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 3692,
    taxes: 226,
    subtotal: 3466,
    childSupport: 0,
    monthlyNet: 3266,
  },
  {
    id: 6,
    career: "Government Inspector",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "8",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 27524,
    montlyGross: 2293,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 3493,
    taxes: 196,
    subtotal: 3297,
    childSupport: 0,
    monthlyNet: 3097,
  },
  {
    id: 7,
    career: "Financial Manager",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "7",
      },
      {
        gender: "boy",
        age: "5",
      },
      {
        gender: "boy",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 73390,
    montlyGross: 6115,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 7315,
    taxes: 666,
    subtotal: 6649,
    childSupport: 0,
    monthlyNet: 6649,
  },
  {
    id: 8,
    career: "Purchasing Manager",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "5",
      },
      {
        gender: "girl",
        age: "5",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 60630,
    montlyGross: 5052,
    spouseGrossIncome: 0,
    totalMonthlyGross: 5052,
    taxes: 380,
    subtotal: 4672,
    childSupport: 0,
    monthlyNet: 4472,
  },
  {
    id: 9,
    career: "Production Manager",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "5",
      },
      {
        gender: "boy",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 64970,
    montlyGross: 5414,
    spouseGrossIncome: 0,
    totalMonthlyGross: 5414,
    taxes: 434,
    subtotal: 4980,
    childSupport: 0,
    monthlyNet: 4980,
  },
  {
    id: 10,
    career: "Communications Manager",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "boy",
        age: "9",
      },
      {
        gender: "girl",
        age: "7",
      },
      {
        gender: "boy",
        age: "2",
      },
      {
        gender: "boy",
        age: "2",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 72410,
    montlyGross: 6034,
    spouseGrossIncome: 0,
    totalMonthlyGross: 6034,
    taxes: 426,
    subtotal: 5608,
    childSupport: 0,
    monthlyNet: 5408,
  },
  {
    id: 11,
    career: "Auditor",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "boy",
        age: "7",
      },
      {
        gender: "girl",
        age: "5",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 47200,
    montlyGross: 3933,
    spouseGrossIncome: 1000,
    totalMonthlyGross: 4933,
    taxes: 362,
    subtotal: 4571,
    childSupport: 0,
    monthlyNet: 4371,
  },
  {
    id: 12,
    career: "Geologist",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "boy",
        age: "5",
      },
      {
        gender: "girl",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 42464,
    montlyGross: 3538,
    spouseGrossIncome: 0,
    totalMonthlyGross: 3538,
    taxes: 151,
    subtotal: 3387,
    childSupport: 0,
    monthlyNet: 3187,
  },
  {
    id: 13,
    career: "Agricultural Scientist",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "5",
      },
      {
        gender: "boy",
        age: "1",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 64600,
    montlyGross: 5383,
    spouseGrossIncome: 0,
    totalMonthlyGross: 5383,
    taxes: 428,
    subtotal: 4955,
    childSupport: 0,
    monthlyNet: 4755,
  },
  {
    id: 14,
    career: "Mathematician",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "7",
      },
      {
        gender: "boy",
        age: "2",
      },
      {
        gender: "boy",
        age: "2",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 66664,
    montlyGross: 5555,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 6755,
    taxes: 582,
    subtotal: 6173,
    childSupport: 0,
    monthlyNet: 5973,
  },
  {
    id: 15,
    career: "Computer Programmer",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "1",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 57600,
    montlyGross: 4800,
    spouseGrossIncome: 0,
    totalMonthlyGross: 4800,
    taxes: 388,
    subtotal: 4412,
    childSupport: 0,
    monthlyNet: 4212,
  },
  {
    id: 16,
    career: "Conservation Officer",
    education: "College",
    edCost: 200,
    children: [],
    maritalStatus: "Single",
    anuualGross: 28480,
    montlyGross: 2373,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2373,
    taxes: 242,
    subtotal: 2131,
    childSupport: 0,
    monthlyNet: 1931,
  },
  {
    id: 17,
    career: "Dentist",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "8",
      },
      {
        gender: "boy",
        age: "6",
      },
      {
        gender: "girl",
        age: "2",
      },
      {
        gender: "girl",
        age: "2",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 120200,
    montlyGross: 10016,
    spouseGrossIncome: 0,
    totalMonthlyGross: 10016,
    taxes: 1170,
    subtotal: 8846,
    childSupport: 0,
    monthlyNet: 8646,
  },
  {
    id: 18,
    career: "Chiropractor",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "boy",
        age: "9",
      },
      {
        gender: "boy",
        age: "7",
      },
      {
        gender: "boy",
        age: "4",
      },
      {
        gender: "boy",
        age: "4",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 95950,
    montlyGross: 7995,
    spouseGrossIncome: 0,
    totalMonthlyGross: 7995,
    taxes: 719,
    subtotal: 7276,
    childSupport: 0,
    monthlyNet: 7076,
  },
  {
    id: 19,
    career: "Nurse--LPN",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "1",
      },
    ],
    maritalStatus: "Divorced",
    custody: true,
    anuualGross: 34281,
    montlyGross: 2856,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2856,
    taxes: 150,
    subtotal: 2706,
    childSupport: 500,
    monthlyNet: 3006,
  },
  {
    id: 20,
    career: "Pharmacist",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "7",
      },
      {
        gender: "boy",
        age: "2",
      },
      {
        gender: "boy",
        age: "2",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 69940,
    montlyGross: 5828,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 7028,
    taxes: 623,
    subtotal: 6405,
    childSupport: 0,
    monthlyNet: 6205,
  },
  {
    id: 21,
    career: "Optometrist",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "5",
      },
      {
        gender: "boy",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 62580,
    montlyGross: 5215,
    spouseGrossIncome: 0,
    totalMonthlyGross: 5215,
    taxes: 404,
    subtotal: 4811,
    childSupport: 0,
    monthlyNet: 4611,
  },
  {
    id: 22,
    career: "Community College Teacher",
    education: "College",
    edCost: 200,
    children: [],
    maritalStatus: "Single",
    anuualGross: 36760,
    montlyGross: 3063,
    spouseGrossIncome: 0,
    totalMonthlyGross: 3063,
    taxes: 344,
    subtotal: 2719,
    childSupport: 0,
    monthlyNet: 2519,
  },
  {
    id: 23,
    career: "Vocational Teacher",
    education: "College",
    edCost: 200,
    children: [],
    maritalStatus: "Single",
    anuualGross: 38100,
    montlyGross: 3175,
    spouseGrossIncome: 0,
    totalMonthlyGross: 3175,
    taxes: 362,
    subtotal: 2813,
    childSupport: 0,
    monthlyNet: 2613,
  },
  {
    id: 24,
    career: "Economist",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "8",
      },
      {
        gender: "boy",
        age: "5",
      },
    ],
    maritalStatus: "Divorced",
    custody: false,
    anuualGross: 76190,
    montlyGross: 6349,
    spouseGrossIncome: 0,
    totalMonthlyGross: 6349,
    taxes: 981,
    subtotal: 5368,
    childSupport: 900,
    monthlyNet: 4268,
  },
  {
    id: 25,
    career: "Social Worker",
    education: "College",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "2",
      },
    ],
    maritalStatus: "Divorced",
    custody: true,
    anuualGross: 35970,
    montlyGross: 2997,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2997,
    taxes: 167,
    subtotal: 2830,
    childSupport: 450,
    monthlyNet: 3080,
  },
  {
    id: 26,
    career: "Optician",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "6",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 28490,
    montlyGross: 2374,
    spouseGrossIncome: 900,
    totalMonthlyGross: 3274,
    taxes: 160,
    subtotal: 3114,
    childSupport: 0,
    monthlyNet: 3114,
  },
  {
    id: 27,
    career: "Dental Hygienist",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "2",
      },
      {
        gender: "girl",
        age: "1",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 59290,
    montlyGross: 4940,
    spouseGrossIncome: 0,
    totalMonthlyGross: 4940,
    taxes: 362,
    subtotal: 4578,
    childSupport: 0,
    monthlyNet: 4578,
  },
  {
    id: 28,
    career: "Legal Assistant",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "6",
      },
      {
        gender: "boy",
        age: "3",
      },
      {
        gender: "boy",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 35570,
    montlyGross: 2964,
    spouseGrossIncome: 1500,
    totalMonthlyGross: 4464,
    taxes: 241,
    subtotal: 4223,
    childSupport: 0,
    monthlyNet: 4223,
  },
  {
    id: 29,
    career: "Power Line Worker",
    education: "Techincal",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "8",
      },
      {
        gender: "girl",
        age: "1",
      },
    ],
    maritalStatus: "Divorced",
    custody: false,
    anuualGross: 42930,
    montlyGross: 3577,
    spouseGrossIncome: 0,
    totalMonthlyGross: 3577,
    taxes: 422,
    subtotal: 3155,
    childSupport: 900,
    monthlyNet: 2255,
  },
  {
    id: 30,
    career: "Carpenter",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "2",
      },
    ],
    maritalStatus: "Widowed",
    anuualGross: 28230,
    montlyGross: 2352,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2352,
    taxes: 98,
    subtotal: 2254,
    childSupport: 0,
    monthlyNet: 2254,
  },
  {
    id: 31,
    career: "Plaster/Dywall Hanger",
    education: "High School",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "5",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 30920,
    montlyGross: 2576,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2576,
    taxes: 89,
    subtotal: 2487,
    childSupport: 0,
    monthlyNet: 2487,
  },
  {
    id: 32,
    career: "Iron Worker",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "6",
      },
      {
        gender: "boy",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 33120,
    montlyGross: 2760,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2760,
    taxes: 72,
    subtotal: 2688,
    childSupport: 0,
    monthlyNet: 2688,
  },
  {
    id: 33,
    career: "Vehicle Mechanic",
    education: "Technical",
    edCost: 0,
    children: [],
    maritalStatus: "Single",
    anuualGross: 32610,
    montlyGross: 2717,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2717,
    taxes: 290,
    subtotal: 2427,
    childSupport: 0,
    monthlyNet: 2427,
  },
  {
    id: 34,
    career: "Railroad Mechanic",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "5",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 37400,
    montlyGross: 3116,
    spouseGrossIncome: 0,
    totalMonthlyGross: 3116,
    taxes: 141,
    subtotal: 2975,
    childSupport: 0,
    monthlyNet: 2975,
  },
  {
    id: 35,
    career: "Millwright",
    education: "Technical",
    edCost: 200,
    children: [
      {
        gender: "girl",
        age: "4",
      },
      {
        gender: "boy",
        age: "1",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 36390,
    montlyGross: 3032,
    spouseGrossIncome: 0,
    totalMonthlyGross: 3032,
    taxes: 100,
    subtotal: 2932,
    childSupport: 0,
    monthlyNet: 2932,
  },
  {
    id: 36,
    career: "Office Machine Manager",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "1",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 31420,
    montlyGross: 2618,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2618,
    taxes: 93,
    subtotal: 2525,
    childSupport: 0,
    monthlyNet: 2525,
  },
  {
    id: 37,
    career: "Appliance Repair",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "7",
      },
      {
        gender: "girl",
        age: "5",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 30830,
    montlyGross: 2569,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 3769,
    taxes: 56,
    subtotal: 3713,
    childSupport: 0,
    monthlyNet: 3713,
  },
  {
    id: 38,
    career: "Toolmaker",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "4",
      },
    ],
    maritalStatus: "Divorced",
    custody: false,
    anuualGross: 32430,
    montlyGross: 2701,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2701,
    taxes: 290,
    subtotal: 2411,
    childSupport: 500,
    monthlyNet: 1911,
  },
  {
    id: 39,
    career: "Sheet Metal Worker",
    education: "Technical",
    edCost: 0,
    children: [],
    maritalStatus: "Single",
    anuualGross: 29620,
    montlyGross: 2468,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2468,
    taxes: 254,
    subtotal: 2214,
    childSupport: 0,
    monthlyNet: 2214,
  },
  {
    id: 40,
    career: "Welder",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "7",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 30430,
    montlyGross: 2535,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 3735,
    taxes: 232,
    subtotal: 3503,
    childSupport: 0,
    monthlyNet: 3503,
  },
  {
    id: 41,
    career: "Woodworker",
    education: "Technical",
    edCost: 0,
    children: [],
    maritalStatus: "Single",
    anuualGross: 29889,
    montlyGross: 2490,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2490,
    taxes: 260,
    subtotal: 2230,
    childSupport: 0,
    monthlyNet: 2230,
  },
  {
    id: 42,
    career: "Firefighter",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "5",
      },
      {
        gender: "girl",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 33630,
    montlyGross: 2802,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2802,
    taxes: 76,
    subtotal: 2726,
    childSupport: 0,
    monthlyNet: 2726,
  },
  {
    id: 43,
    career: "Chef",
    education: "Technical",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "5",
      },
      {
        gender: "boy",
        age: "2",
      },
    ],
    maritalStatus: "Divorced",
    custody: true,
    anuualGross: 30560,
    montlyGross: 2546,
    spouseGrossIncome: 0,
    totalMonthlyGross: 3346,
    taxes: 85,
    subtotal: 3261,
    childSupport: 500,
    monthlyNet: 3761,
  },
  {
    id: 44,
    career: "Paramedic",
    education: "Technical",
    edCost: 0,
    children: [],
    maritalStatus: "Single",
    anuualGross: 23810,
    montlyGross: 1984,
    spouseGrossIncome: 0,
    totalMonthlyGross: 1984,
    taxes: 182,
    subtotal: 1802,
    childSupport: 0,
    monthlyNet: 1802,
  },
  {
    id: 45,
    career: "Nurses Aid",
    education: "High School",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "1",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 17930,
    montlyGross: 1494,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 2694,
    taxes: 101,
    subtotal: 2593,
    childSupport: 0,
    monthlyNet: 2593,
  },
  {
    id: 46,
    career: "Painter",
    education: "High School",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "5",
      },
      {
        gender: "boy",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 25540,
    montlyGross: 2128,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2128,
    taxes: 12,
    subtotal: 2116,
    childSupport: 0,
    monthlyNet: 2116,
  },
  {
    id: 47,
    career: "Aircraft Manfacturing",
    education: "High School",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "2",
      },
      {
        gender: "girl",
        age: "1",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 41314,
    montlyGross: 3442,
    spouseGrossIncome: 0,
    totalMonthlyGross: 3442,
    taxes: 140,
    subtotal: 3302,
    childSupport: 0,
    monthlyNet: 3302,
  },
  {
    id: 48,
    career: "Cabinet/Furniture Maker",
    education: "high School",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "3",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 23330,
    montlyGross: 1944,
    spouseGrossIncome: 1000,
    totalMonthlyGross: 2944,
    taxes: 145,
    subtotal: 2799,
    childSupport: 0,
    monthlyNet: 2799,
  },
  {
    id: 49,
    career: "Upholsterer",
    education: "High School",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "8",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 22030,
    montlyGross: 1835,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 3035,
    taxes: 133,
    subtotal: 2902,
    childSupport: 0,
    monthlyNet: 2902,
  },
  {
    id: 50,
    career: "Furnace Operator",
    education: "High School",
    edCost: 0,
    children: [],
    maritalStatus: "Single",
    anuualGross: 26910,
    montlyGross: 2242,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2242,
    taxes: 224,
    subtotal: 2018,
    childSupport: 0,
    monthlyNet: 2018,
  },
  {
    id: 51,
    career: "Meat Cutter",
    education: "High School",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "2",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 24140,
    montlyGross: 2011,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2011,
    taxes: 33,
    subtotal: 1978,
    childSupport: 0,
    monthlyNet: 1978,
  },
  {
    id: 52,
    career: "Textile Worker",
    education: "Technical",
    edCost: 0,
    children: [],
    maritalStatus: "Single",
    anuualGross: 20150,
    montlyGross: 1679,
    spouseGrossIncome: 0,
    totalMonthlyGross: 1679,
    taxes: 134,
    subtotal: 1545,
    childSupport: 0,
    monthlyNet: 1545,
  },
  {
    id: 53,
    career: "Tree Cutter Operator",
    education: "High School",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "5",
      },
      {
        gender: "girl",
        age: "5",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 25070,
    montlyGross: 2089,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2089,
    taxes: 8,
    subtotal: 2081,
    childSupport: 0,
    monthlyNet: 2081,
  },
  {
    id: 54,
    career: "Animal Farmer",
    education: "High School",
    edCost: 0,
    children: [],
    maritalStatus: "Single",
    anuualGross: 17690,
    montlyGross: 1474,
    spouseGrossIncome: 0,
    totalMonthlyGross: 1474,
    taxes: 104,
    subtotal: 1370,
    childSupport: 0,
    monthlyNet: 1370,
  },
  {
    id: 55,
    career: "Farm Worker",
    education: "Dropout",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "2",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 15780,
    montlyGross: 1315,
    spouseGrossIncome: 1000,
    totalMonthlyGross: 2315,
    taxes: 61,
    subtotal: 2254,
    childSupport: 0,
    monthlyNet: 2254,
  },
  {
    id: 56,
    career: "Farm Machine Operator",
    education: "Dropout",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "4",
      },
    ],
    maritalStatus: "Divorced",
    custody: false,
    anuualGross: 25860,
    montlyGross: 2155,
    spouseGrossIncome: 0,
    totalMonthlyGross: 2155,
    taxes: 206,
    subtotal: 1949,
    childSupport: 500,
    monthlyNet: 1449,
  },
  {
    id: 57,
    career: "Waiter/Waitress",
    education: "High School",
    edCost: 0,
    children: [
      {
        gender: "girl",
        age: "1",
      },
    ],
    maritalStatus: "Divorced",
    custody: true,
    anuualGross: 14600,
    montlyGross: 1216,
    spouseGrossIncome: 0,
    totalMonthlyGross: 1216,
    taxes: 0,
    subtotal: 1216,
    childSupport: 500,
    monthlyNet: 1716,
  },
  {
    id: 58,
    career: "Dry Clean Worker",
    education: "Dropout",
    edCost: 0,
    children: [
      {
        gender: "boy",
        age: "5",
      },
    ],
    maritalStatus: "Married",
    anuualGross: 15920,
    montlyGross: 1326,
    spouseGrossIncome: 1200,
    totalMonthlyGross: 2526,
    taxes: 85,
    subtotal: 2441,
    childSupport: 0,
    monthlyNet: 2441,
  },
];

var housingOptions = [
  {
    id: 0,
    type: "apartment",
    description: "One Bedroom/One Bathroom Apartment",
    rent: 395,
    insurance: 15,
    totalDue: 410,
    squareFt: 757,
    photo: "../images/OneBedroomOneBath.jpg",
  },
  {
    id: 1,
    type: "apartment",
    description: "Two Bedroom/Two Bathroom Apartment",
    rent: 625,
    insurance: 25,
    totalDue: 650,
    squareFt: 1138,
    photo: "../images/TwoBedroomTwoBath.jpg",
  },
  {
    id: 2,
    type: "apartment",
    description: "Three Bedroom/Two Bathroom Apartment",
    rent: 750,
    insurance: 30,
    totalDue: 780,
    squareFt: 1425,
    photo: "../images/ThreeBedroom.jpg",
  },
  {
    id: 3,
    type: "house",
    description: "Two Bedroom Home",
    mortgage: 400,
    taxes: 0,
    insurance: 50,
    totalDue: 450,
    photo: "../images/TwoBedHouse.jpg",
  },
  {
    id: 4,
    type: "house",
    description: "Three Bedroom Home",
    mortgage: 658,
    taxes: 125,
    insurance: 40,
    totalDue: 823,
    photo: "../images/ThreeBedHouse.jpg",
  },
  {
    id: 5,
    type: "house",
    description: "Four Bedroom Home",
    mortgage: 1368,
    taxes: 250,
    insurance: 78,
    totalDue: 1650,
    photo: "../images/FourBedHouse.jpg",
  },
];

var transportOptions = [
  {
    id: 0,
    make: "Nissan",
    model: "Frontier",
    year: 2015,
    cost: 23000,
    monthlyPymt: 245,
    insurance: 125,
    gas: 125,
    total: 495,
    description: "Can hold 2 adults and two children",
    photo: "../images/frontier.jpg",
  },
  {
    id: 1,
    make: "Ford",
    model: "Mustang",
    year: 2014,
    cost: 27958,
    monthlyPymt: 425,
    insurance: 69,
    gas: 156,
    total: 650,
    description: "Can hold 2 adults and 1 child",
    photo: "../images/mustang.jpg",
  },
  {
    id: 2,
    make: "Cadillac",
    model: "SRX Premium",
    year: 2015,
    cost: 40000,
    monthlyPymt: 500,
    insurance: 125,
    gas: 110,
    total: 735,
    description: "Can hold 2 adults and 3 children",
    photo: "../images/srx.jpg",
  },
  {
    id: 3,
    make: "Chevy",
    model: "Suburban 1500 LT",
    year: 2013,
    cost: 31992,
    monthlyPymt: 590,
    insurance: 75,
    gas: 225,
    total: 890,
    description: "Can hold 2 adults and 5 children",
    photo: "../images/suburban.jpg",
  },
  {
    id: 4,
    make: "Ford",
    model: "Ranger",
    year: 1994,
    cost: 7999,
    monthlyPymt: 145,
    insurance: 55,
    gas: 100,
    total: 300,
    description: "Can hold 2 adults or 1 adult",
    photo: "../images/ranger.jpg",
  },
  {
    id: 5,
    make: "Honda",
    model: "Civic",
    year: 2015,
    cost: 15990,
    monthlyPymt: 185,
    insurance: 65,
    gas: 150,
    total: 400,
    description: "Can hold 2 adults and 2 children",
    photo: "../images/civic.jpg",
  },
];
